# Generated by Django 5.0.1 on 2024-01-12 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_company_employee_departments_employee_user'),
        ('overtime_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
            preserve_default=False,
        ),
    ]
